//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wags.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Club:IEntity
    {
        public Club()
        {
            this.Courses = new HashSet<Course>();
            this.Address = new Address();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
        public string Phone { get; set; }
        public string Directions { get; set; }
    
        public Address Address { get; set; }
    
        public virtual ICollection<Course> Courses { get; set; }
    }
}
