//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wags.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseData
    {
        public int Id { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public Nullable<int> SSS { get; set; }
        public int Par { get; set; }
        public int CourseId { get; set; }
    
        public virtual Course Course { get; set; }
    }
}
