//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wags.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public Course()
        {
            this.CourseData = new HashSet<CourseData>();
            this.Rounds = new HashSet<Round>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int ClubId { get; set; }
    
        public virtual ICollection<CourseData> CourseData { get; set; }
        public virtual Club Club { get; set; }
        public virtual ICollection<Round> Rounds { get; set; }
    }
}
