//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wags.DataModel
{
    using System;
    
    public enum PlayerStatus : int
    {
        Guest = 0,
        Member = 1,
        ExWag = 2,
        Overseas = 3
    }
}
