//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wags.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Round:IEntity
    {
        public Round()
        {
            this.Scores = new HashSet<Score>();
        }
    
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int EventId { get; set; }
        public int CourseId { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual ICollection<Score> Scores { get; set; }
        public virtual Course Course { get; set; }
    }
}
